spring:
  r2dbc:
    url: r2dbc:h2:file:///./dataStore/mydb
    username: sa
    password:
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    url: jdbc:h2:file:./dataStore/mydb
    user: sa
    password: