package rules.movement;

import com.interdimensionalmallet.twtpthvtt.model.*;
import com.interdimensionalmallet.twtpthvtt.rules.ProposedEvent;

dialect "mvel";

rule "Start Movement Query"
    when
        $resource: Resource(name == "movement_spaces", count > 0)
    then
        System.out.println("Start Movement Query");
        long thingId = idCaches.nextThingId();
        insert(new ProposedEvent(Event.thingEvent(Event.EventType.CREATE, thingId, "Movement query thing")));
        insert(new ProposedEvent(Event.resourceEvent(Event.EventType.CREATE, idCaches.nextResourceId(), thingId, "movement_query", 1)));
        insert(new ProposedEvent(Event.linkEvent(Event.EventType.CREATE,  thingId, $resource.thingId)));
end