CREATE SEQUENCE RESOURCE_ID_SEQ;

CREATE TABLE RESOURCE (
  ID BIGINT PRIMARY KEY,
  THING_ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  COUNT INT NOT NULL,
  DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (THING_ID) REFERENCES THING(ID)
);

CREATE INDEX IDX_RESOURCE_THING_ID ON RESOURCE(THING_ID);
CREATE INDEX IDX_RESOURCE_NAME ON RESOURCE(NAME);