CREATE TABLE LINK (
    SOURCE_THING_ID BIGINT NOT NULL,
    TARGET_THING_ID BIGINT NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (SOURCE_THING_ID) REFERENCES THING(ID),
    FOREIGN KEY (TARGET_THING_ID) REFERENCES THING(ID),
    PRIMARY KEY (SOURCE_THING_ID, TARGET_THING_ID)
);