CREATE SEQUENCE LINK_ID_SEQ;

CREATE TABLE LINK (
    ID BIGINT PRIMARY KEY,
    SOURCE_THING_ID BIGINT NOT NULL,
    TARGET_THING_ID BIGINT NOT NULL,
    FOREIGN KEY (SOURCE_THING_ID) REFERENCES THING(ID),
    FOREIGN KEY (TARGET_THING_ID) REFERENCES THING(ID)
);