CREATE SEQUENCE EVENT_ID_SEQ;

CREATE TABLE EVENT (
    ID BIGINT PRIMARY KEY,
    PREVIOUS_ID BIGINT,
    NEXT_ID BIGINT,
    EVENT_TYPE VARCHAR(255) NOT NULL,
    EVENT_STYLE VARCHAR(255) NOT NULL,
    THING_ID BIGINT,
    THING_NAME VARCHAR(255),
    LINK_ID BIGINT,
    TARGET_THING_ID BIGINT,
    RESOURCE_ID BIGINT,
    RESOURCE_NAME VARCHAR(255),
    RESOURCE_MODIFIER INT,
    FOREIGN KEY (PREVIOUS_ID) REFERENCES EVENT(ID),
    FOREIGN KEY (NEXT_ID) REFERENCES EVENT(ID)
);

CREATE TABLE CURRENT_EVENT (
    EVENT_ID BIGINT PRIMARY KEY,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID)
);