CREATE SEQUENCE QUERY_ID_SEQ;
CREATE SEQUENCE QUERY_OPTION_ID_SEQ;

CREATE TABLE QUERY (
  ID BIGINT PRIMARY KEY,
  QUERY_NAME VARCHAR(1024) NOT NULL,
  TARGET_ID BIGINT,
  SELECTED_OPTION_ID BIGINT,
  DELETED BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE QUERY_OPTION (
  ID BIGINT PRIMARY KEY,
  QUERY_ID BIGINT NOT NULL,
  STRING_OPTION VARCHAR(1024),
  ID_OPTION BIGINT,
  DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (QUERY_ID) REFERENCES QUERY(ID)
);

ALTER TABLE QUERY ADD FOREIGN KEY (SELECTED_OPTION_ID) REFERENCES QUERY_OPTION(ID);